# Generated by Django 5.0 on 2024-06-01 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_clientdates_date_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='popo', max_length=64),
        ),
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 15, 24, 803125)),
        ),
    ]
