# Generated by Django 5.0 on 2024-07-05 20:53

import datetime
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_doctor_city_alter_clientdates_date_alter_clinic_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='days',
        ),
        migrations.RemoveField(
            model_name='dates',
            name='horas',
        ),
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 16, 53, 13, 581653)),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.AddField(
            model_name='dates',
            name='days',
            field=web.models.MultiSelectField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='Santo Domingo', max_length=64),
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.AddField(
            model_name='dates',
            name='horas',
            field=web.models.MultiSelectField(choices=[(0, 0), (1, 3600000), (2, 7200000), (3, 10800000), (4, 14400000), (5, 18000000), (6, 21600000), (7, 25200000), (8, 28800000), (9, 32400000), (10, 36000000), (11, 39600000), (12, 43200000), (13, 46800000), (14, 50400000), (15, 54000000), (16, 57600000), (17, 61200000), (18, 64800000), (19, 68400000), (20, 72000000), (21, 75600000), (22, 79200000), (23, 82800000)], default='Santo Domingo', max_length=64),
        ),
    ]
