# Generated by Django 5.0 on 2024-07-12 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_clientdates_time_alter_clientdates_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 20, 46, 11, 622848)),
        ),
    ]
