# Generated by Django 5.0 on 2024-07-12 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_clientdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 11, 20, 48, 21, 486029)),
        ),
    ]
