# Generated by Django 5.0 on 2024-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='https://i.imgflip.com/6yvpkj.jpg'),
        ),
    ]
