# Generated by Django 5.0 on 2024-09-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_dates_clinica_remove_dates_days_and_more'),
        ('web', '0023_user_ensurance'),
    ]

    operations = [
    ]
