# Generated by Django 5.0 on 2024-09-24 02:13

import django.db.models.deletion
import phonenumber_field.modelfields
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_merge_20240923_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=web.models.MultiSelectField(choices=[('Distrito Nacional', 'Distrito Nacional'), ('Azua', 'Azua'), ('Baoruco', 'Baoruco'), ('Barahona', 'Barahona'), ('Dajabón', 'Dajabón'), ('Duarte', 'Duarte'), ('Elías Piña', 'Elías Piña'), ('El Seibo', 'El Seibo'), ('Espaillat', 'Espaillat'), ('Independencia', 'Independencia'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('La Vega', 'La Vega'), ('María Trinidad Sánchez', 'María Trinidad Sánchez'), ('Monte Cristi', 'Monte Cristi'), ('Pedernales', 'Pedernales'), ('Peravia', 'Peravia'), ('Puerto Plata', 'Puerto Plata'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('Samaná', 'Samaná'), ('San Cristóbal', 'San Cristóbal'), ('San Juan', 'San Juan'), ('San Pedro de Macorís', 'San Pedro de Macorís'), ('Sanchez Ramírez', 'Sanchez Ramírez'), ('Santiago', 'Santiago'), ('Santiago Rodríguez', 'Santiago Rodríguez'), ('Valverde', 'Valverde'), ('Monseñor Nouel', 'Monseñor Nouel'), ('Monte Plata', 'Monte Plata'), ('Hato Mayor', 'Hato Mayor'), ('San José de Ocoa', 'San José de Ocoa'), ('Santo Domingo', 'Santo Domingo')], default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cities',
            field=web.models.MultiSelectField(choices=[('Distrito Nacional', 'Distrito Nacional'), ('Azua', 'Azua'), ('Baoruco', 'Baoruco'), ('Barahona', 'Barahona'), ('Dajabón', 'Dajabón'), ('Duarte', 'Duarte'), ('Elías Piña', 'Elías Piña'), ('El Seibo', 'El Seibo'), ('Espaillat', 'Espaillat'), ('Independencia', 'Independencia'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('La Vega', 'La Vega'), ('María Trinidad Sánchez', 'María Trinidad Sánchez'), ('Monte Cristi', 'Monte Cristi'), ('Pedernales', 'Pedernales'), ('Peravia', 'Peravia'), ('Puerto Plata', 'Puerto Plata'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('Samaná', 'Samaná'), ('San Cristóbal', 'San Cristóbal'), ('San Juan', 'San Juan'), ('San Pedro de Macorís', 'San Pedro de Macorís'), ('Sanchez Ramírez', 'Sanchez Ramírez'), ('Santiago', 'Santiago'), ('Santiago Rodríguez', 'Santiago Rodríguez'), ('Valverde', 'Valverde'), ('Monseñor Nouel', 'Monseñor Nouel'), ('Monte Plata', 'Monte Plata'), ('Hato Mayor', 'Hato Mayor'), ('San José de Ocoa', 'San José de Ocoa'), ('Santo Domingo', 'Santo Domingo')], default='Santo Domingo', max_length=64),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='web.clinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='docuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ensurances',
            field=models.ManyToManyField(related_name='doctors', to='web.ensurance'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(default='00:00', max_length=5)),
                ('isActive', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientDates', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientDates', to='web.clinic')),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientDates', to='web.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('instagram', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='web.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('days', web.models.MultiSelectField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), ('web', 'days')], max_length=300)),
                ('horas', web.models.MultiSelectField(choices=[('0:00', '0:00'), ('0:30', '0:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30')], max_length=300)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Ambas', 'Ambas'), ('web', 'days')], max_length=300)),
                ('clinica', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='web.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='web.doctor')),
                ('especialidad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='web.speciality')),
            ],
        ),
    ]
