# Generated by Django 5.0 on 2024-09-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_doctor_city_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ensurance',
            field=models.ManyToManyField(related_name='ensurances', to='web.ensurance'),
        ),
    ]
