# Generated by Django 5.0 on 2024-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_doctor_age_user_recent_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_doctors',
            field=models.ManyToManyField(to='web.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
