# Generated by Django 5.0 on 2024-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_user_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='renderizable',
            field=models.BooleanField(default=False),
        ),
    ]
