# Generated by Django 5.0 on 2024-10-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_remove_doctor_experience_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ensurance',
            field=models.ManyToManyField(blank=True, related_name='ensurances', to='web.ensurance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recent_doctors',
            field=models.ManyToManyField(blank=True, to='web.doctor'),
        ),
    ]
