# Generated by Django 5.0 on 2024-10-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_user_ensurance_alter_user_recent_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bornDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
