# Generated by Django 5.0 on 2024-10-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_doctor_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensurance',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
