# Generated by Django 5.0 on 2024-10-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_remove_user_image_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
    ]
