# Generated by Django 5.0 on 2024-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_remove_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='static/images/profile_picture.jpg', upload_to='static/images'),
        ),
    ]
