# Generated by Django 5.0 on 2024-12-06 20:46

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_doctor_in_person_doctor_takes_dates_doctor_virtually'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(choices=[('Azua', 'Azua'), ('Baoruco', 'Baoruco'), ('Barahona', 'Barahona'), ('Dajabón', 'Dajabón'), ('Duarte', 'Duarte'), ('Elías Piña', 'Elías Piña'), ('El Seibo', 'El Seibo'), ('Espaillat', 'Espaillat'), ('Independencia', 'Independencia'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('La Vega', 'La Vega'), ('María Trinidad Sánchez', 'María Trinidad Sánchez'), ('Monte Cristi', 'Monte Cristi'), ('Pedernales', 'Pedernales'), ('Peravia', 'Peravia'), ('Puerto Plata', 'Puerto Plata'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('Samaná', 'Samaná'), ('San Cristóbal', 'San Cristóbal'), ('San Juan', 'San Juan'), ('San Pedro de Macorís', 'San Pedro de Macorís'), ('Sanchez Ramírez', 'Sanchez Ramírez'), ('Santiago', 'Santiago'), ('Santiago Rodríguez', 'Santiago Rodríguez'), ('Valverde', 'Valverde'), ('Monseñor Nouel', 'Monseñor Nouel'), ('Monte Plata', 'Monte Plata'), ('Hato Mayor', 'Hato Mayor'), ('San José de Ocoa', 'San José de Ocoa'), ('Santo Domingo', 'Santo Domingo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cities',
            field=web.models.MultiSelectField(blank=True, choices=[('Azua', 'Azua'), ('Baoruco', 'Baoruco'), ('Barahona', 'Barahona'), ('Dajabón', 'Dajabón'), ('Duarte', 'Duarte'), ('Elías Piña', 'Elías Piña'), ('El Seibo', 'El Seibo'), ('Espaillat', 'Espaillat'), ('Independencia', 'Independencia'), ('La Altagracia', 'La Altagracia'), ('La Romana', 'La Romana'), ('La Vega', 'La Vega'), ('María Trinidad Sánchez', 'María Trinidad Sánchez'), ('Monte Cristi', 'Monte Cristi'), ('Pedernales', 'Pedernales'), ('Peravia', 'Peravia'), ('Puerto Plata', 'Puerto Plata'), ('Hermanas Mirabal', 'Hermanas Mirabal'), ('Samaná', 'Samaná'), ('San Cristóbal', 'San Cristóbal'), ('San Juan', 'San Juan'), ('San Pedro de Macorís', 'San Pedro de Macorís'), ('Sanchez Ramírez', 'Sanchez Ramírez'), ('Santiago', 'Santiago'), ('Santiago Rodríguez', 'Santiago Rodríguez'), ('Valverde', 'Valverde'), ('Monseñor Nouel', 'Monseñor Nouel'), ('Monte Plata', 'Monte Plata'), ('Hato Mayor', 'Hato Mayor'), ('San José de Ocoa', 'San José de Ocoa'), ('Santo Domingo', 'Santo Domingo')], max_length=64),
        ),
    ]
