# Generated by Django 5.0 on 2024-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_remove_doctor_gender_review_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exequatur',
            field=models.CharField(blank=True, help_text='Dominican Exequatur number assigned by authorities', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='Dominican National ID (Cédula), e.g. 001-1234567-8', max_length=13, null=True, unique=True),
        ),
    ]
