# Generated by Django 5.0 on 2024-12-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_user_exequatur_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdate',
            name='time',
            field=models.TimeField(),
        ),
    ]
