# Generated by Django 5.0 on 2024-12-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_alter_clientdate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordate',
            name='especialidad',
        ),
    ]
