# Generated by Django 5.0 on 2024-12-31 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_remove_doctordate_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordate',
            name='clinica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='web.clinic'),
        ),
        migrations.AlterField(
            model_name='doctordate',
            name='precio',
            field=models.IntegerField(default=100),
        ),
    ]
