# Generated by Django 5.0 on 2024-12-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_alter_doctordate_clinica_alter_doctordate_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordate',
            name='clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='web.clinic'),
        ),
    ]
