# Generated by Django 5.0 on 2025-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_doctordate_horas_alter_doctordate_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordate',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
