# Generated by Django 5.0 on 2024-05-16 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.URLField(default='https://i.imgflip.com/6yvpkj.jpg'),
        ),
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 12, 16, 3, 521499)),
        ),
    ]
