# Generated by Django 5.0 on 2024-05-16 17:24

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_profilepicture_alter_clientdates_date'),
    ]

    operations = [

        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 13, 24, 46, 792713)),
        ),
    ]
