# Generated by Django 5.0 on 2024-07-05 21:06

import datetime
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_dates_days_remove_dates_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 17, 6, 11, 696473)),
        ),
        migrations.AlterField(
            model_name='dates',
            name='days',
            field=web.models.MultiSelectField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=300),
        ),
        migrations.AlterField(
            model_name='dates',
            name='horas',
            field=web.models.MultiSelectField(choices=[(0, 0), ('0:30', '0:30'), (1, 1), ('1:30', '1:30'), (2, 2), ('2:30', '2:30'), (3, 3), ('3:30', '3:30'), (4, 4), ('4:30', '4:30'), (5, 5), ('5:30', '5:30'), (6, 6), ('6:30', '6:30'), (7, 7), ('7:30', '7:30'), (8, 8), ('8:30', '8:30'), (9, 9), ('9:30', '9:30'), (10, 10), ('10:30', '10:30'), (11, 11), ('11:30', '11:30'), (12, 12), ('12:30', '12:30'), (13, 13), ('13:30', '13:30'), (14, 14), ('14:30', '14:30'), (15, 15), ('15:30', '15:30'), (16, 16), ('16:30', '16:30'), (17, 17), ('17:30', '17:30'), (18, 18), ('18:30', '18:30'), (19, 19), ('19:30', '19:30'), (20, 20), ('20:30', '20:30'), (21, 21), ('21:30', '21:30'), (22, 22), ('22:30', '22:30'), (23, 23), ('23:30', '23:30')], max_length=300),
        ),
    ]
