# Generated by Django 5.0 on 2024-07-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_clientdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdates',
            name='date',
            field=models.DateField(),
        ),
    ]
