# Generated by Django 5.0 on 2024-08-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='map',
            field=models.CharField(default='hola', max_length=500),
        ),
    ]
