# Generated by Django 5.0 on 2024-08-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_clinic_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ensurance',
            field=models.ManyToManyField(to='web.ensurance'),
        ),
    ]
