# Generated by Django 5.0 on 2024-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_user_recent_doctors_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
