# Generated by Django 5.0 on 2024-10-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_doctor_renderizable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
    ]
