# Generated by Django 5.0 on 2024-10-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_user_borndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Dra.'), ('male', 'Dr.')], max_length=6, null=True),
        ),
    ]
