# Generated by Django 5.0 on 2024-10-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_ensurance_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/profile_picture.jpg', upload_to=''),
        ),
    ]
