# Generated by Django 5.0 on 2024-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='web/static/images/profile_picture.jpg', upload_to='web/static/images'),
        ),
    ]
