# Generated by Django 5.0 on 2024-11-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_alter_doctor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdate',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='clientdate',
            name='doctor',
        ),
        migrations.AddField(
            model_name='clientdate',
            name='date_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients_dates', to='web.doctordate'),
        ),
    ]
