# Generated by Django 5.0 on 2024-11-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_remove_clientdate_clinic_remove_clientdate_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='speciality',
            new_name='name',
        ),
    ]
