# Generated by Django 5.0 on 2024-12-03 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_doctordate_days_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
