# Generated by Django 5.0 on 2024-12-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='takes_dates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='virtually',
            field=models.BooleanField(default=False),
        ),
    ]
