# Generated by Django 5.0 on 2024-12-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_doctor_date_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date_type',
        ),
        migrations.AddField(
            model_name='doctor',
            name='in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='virtually',
            field=models.BooleanField(default=False),
        ),
    ]
