# Generated by Django 5.0 on 2024-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_remove_doctor_date_type_doctor_in_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.AddField(
            model_name='review',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
