# Generated by Django 5.0 on 2025-01-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_clientdate_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdate',
            name='modality',
            field=models.CharField(choices=[('in_person', 'in_person'), ('virtually', 'virtually')], max_length=300),
        ),
    ]
