# Generated by Django 5.0 on 2025-01-07 00:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_doctorcontacts_phone_doctorpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
