# Generated by Django 5.0 on 2025-01-10 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('web', '0071_alter_doctorpatient_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdate',
            name='client',
        ),
        migrations.AddField(
            model_name='clientdate',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdate',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
