# Generated by Django 5.0 on 2025-01-22 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_remove_clientdate_client_clientdate_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='docuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
